DROP TABLE DM_DATETIME;
ALTER SESSION SET NLS_DATE_LANGUAGE = Portuguese;
CREATE TABLE DM_DATETIME
   (DC_DATETIME_PK 		  NUMBER(20) NOT NULL, 
	DC_DATE 			  DATE,    
	DC_UTIL 			  NUMBER(1),
	DC_NUM_DIA 			  NUMBER(2), 
	DC_NUM_MES 			  NUMBER(2),
	DC_NUM_ANO 			  NUMBER(4),
    DC_NUM_ANO_MES        NUMBER(6),
    DC_NUM_ANO_MES_DIA    NUMBER(8),
	DC_NUM_DIA_ANO 		  NUMBER(3),
	DC_NUM_DIA_SEMANA 	  NUMBER(1),
	DC_NUM_SEMANA_MES 	  NUMBER(1),
	DC_NUM_SEMANA_ANO 	  NUMBER(2),
	DC_NUM_SEMESTRE 	  NUMBER(8),
	DC_NUM_QUADRIMESTRE   NUMBER(8),
	DC_NUM_TRIMESTRE 	  NUMBER(8),
	DC_NUM_BIMESTRE 	  NUMBER(8),
	DC_NUM_QUINZENA 	  NUMBER(2),
	DC_DSC_DIA_SEMANA     VARCHAR2(25),
	DC_DSC_DIA_SEMANA_ABV VARCHAR2(10),
	DC_DSC_MES 		      VARCHAR2(20),
	DC_DSC_MES_ABREV      VARCHAR2(10),
	DC_DSC_SEMESTRE       VARCHAR2(120),
	DC_DSC_QUADRIMESTRE   VARCHAR2(120),
	DC_DSC_TRIMESTRE      VARCHAR2(120),
	DC_DSC_BIMESTRE       VARCHAR2(120),
	DC_DSC_QUINZENA       VARCHAR2(120),
	CONSTRAINT PK_DC_DATETIME PRIMARY KEY (DC_DATETIME_PK)
   );
   
DECLARE
	DATA 		DATE;
	DataIni 	DATE;
	DataFim 	DATE;
	Data_Movel 	DATE;
    TMP_DC_DATETIME_PK 		  NUMBER(20); 
	TMP_DC_DATE 			  DATE     ;
	TMP_DC_UTIL 			  NUMBER(1);
	TMP_DC_NUM_DIA 			  NUMBER(2);
	TMP_DC_NUM_MES 			  NUMBER(2);
	TMP_DC_NUM_ANO 			  NUMBER(4);
    TMP_DC_NUM_ANO_MES        NUMBER(6);
    TMP_DC_NUM_ANO_MES_DIA    NUMBER(8);
	TMP_DC_NUM_DIA_ANO 		  NUMBER(3);
	TMP_DC_NUM_DIA_SEMANA 	  NUMBER(1);
	TMP_DC_NUM_SEMANA_MES 	  NUMBER(1);
	TMP_DC_NUM_SEMANA_ANO 	  NUMBER(2);
	TMP_DC_NUM_SEMESTRE 	  NUMBER(6);
	TMP_DC_NUM_QUADRIMESTRE   NUMBER(6);
	TMP_DC_NUM_TRIMESTRE 	  NUMBER(6);
	TMP_DC_NUM_BIMESTRE 	  NUMBER(6);
	TMP_DC_NUM_QUINZENA 	  NUMBER(2);   
	TMP_DC_DSC_DIA_SEMANA     VARCHAR2(25);
	TMP_DC_DSC_DIA_SEMANA_ABV VARCHAR2(10);
	TMP_DC_DSC_MES 		      VARCHAR2(20);
	TMP_DC_DSC_MES_ABREV      VARCHAR2(10);
	TMP_DC_DSC_SEMESTRE       VARCHAR2(120);
	TMP_DC_DSC_QUADRIMESTRE   VARCHAR2(120);
	TMP_DC_DSC_TRIMESTRE      VARCHAR2(120);
	TMP_DC_DSC_BIMESTRE       VARCHAR2(120);
	TMP_DC_DSC_QUINZENA       VARCHAR2(120);
	NUM_SEMESTRE 	  		  VARCHAR2(2);
	NUM_QUADRIMESTRE   		  VARCHAR2(2);
	NUM_TRIMESTRE 	  	  	  VARCHAR2(2);
	NUM_BIMESTRE 	  		  VARCHAR2(2);

BEGIN
  DataIni := to_date('2000/01/01','yyyy/mm/dd');
  DataFim := to_date('2030/12/31','yyyy/mm/dd');
  DATA := DataIni;
  
WHILE DATA <= DataFim LOOP 
      TMP_DC_DATETIME_PK := TO_NUMBER(TO_CHAR(DATA ,'YYYYMMDD'));
	  TMP_DC_DATE := DATA;     
	  --SELECT TO_NUMBER(DECODE(TO_NUMBER(TO_CHAR(DATA ,'D')), 1, '1', 2, '0', 3, '0', 4, '0', 5, '0', 6, '0', 7, '1')) INTO TMP_DC_UTIL FROM DUAL;
	  SELECT TO_NUMBER(DECODE(TO_NUMBER(TO_CHAR(DATA ,'D')), 1, '1', 7, '1', '0')) INTO TMP_DC_UTIL FROM DUAL;
	  TMP_DC_NUM_DIA := TO_NUMBER(TO_CHAR(DATA ,'DD'));
	  TMP_DC_NUM_MES := TO_NUMBER(TO_CHAR(DATA ,'MM'));
	  TMP_DC_NUM_ANO := TO_NUMBER(TO_CHAR(DATA ,'YYYY'));
	  TMP_DC_NUM_ANO_MES_DIA  := TO_NUMBER(TO_CHAR(DATA ,'YYYYMMDD'));
	  TMP_DC_NUM_ANO_MES 	  := TO_NUMBER(TO_CHAR(DATA ,'YYYYMM')); 
	  TMP_DC_NUM_DIA_ANO 	  := TO_NUMBER(TO_CHAR(DATA ,'DDD'));
	  TMP_DC_NUM_DIA_SEMANA   := TO_NUMBER(TO_CHAR(DATA ,'D'));
	  TMP_DC_NUM_SEMANA_MES   := TO_NUMBER(TO_CHAR(DATA ,'W'));
	  TMP_DC_NUM_SEMANA_ANO   := TO_NUMBER(TO_CHAR(DATA ,'WW')); 
	  --SELECT DECODE(TO_NUMBER(TO_CHAR(DATA,'Q')), 1, '01', 2, '01', 3, '02', 4, '02') INTO NUM_SEMESTRE FROM DUAL;
	  --NUM_QUADRIMESTRE := LPAD(TO_CHAR(DATA ,'Q'), 2, '0');
	  --SELECT DECODE(TO_NUMBER(TO_CHAR(DATA,'MM')), 1, '01', 2, '01', 3, '01', 4, '02', 5, '02', 6, '02', 7, '03', 8, '03', 9, '03', 10, '04', 11, '04', 12, '04') INTO NUM_TRIMESTRE FROM DUAL;
	  --SELECT DECODE(TO_NUMBER(TO_CHAR(DATA,'MM')), 1, '01', 2, '01', 3, '02', 4, '02', 5, '03', 6, '03', 7, '04', 8, '04', 9, '05', 10, '05', 11, '06', 12, '06') INTO NUM_BIMESTRE FROM DUAL;
	  SELECT LPAD(TRUNC((TMP_DC_NUM_MES - 1)/6, 0) + 1, 2, '0') INTO NUM_SEMESTRE FROM DUAL;
	  SELECT LPAD(TRUNC((TMP_DC_NUM_MES - 1)/4, 0) + 1, 2, '0') INTO NUM_QUADRIMESTRE FROM DUAL;
	  SELECT LPAD(TRUNC((TMP_DC_NUM_MES - 1)/3, 0) + 1, 2, '0') INTO NUM_TRIMESTRE FROM DUAL;
	  SELECT LPAD(TRUNC((TMP_DC_NUM_MES - 1)/2, 0) + 1, 2, '0') INTO NUM_BIMESTRE FROM DUAL;
	  TMP_DC_NUM_QUINZENA       := TRUNC((TMP_DC_NUM_DIA-1)/15, 0) + 1;
	  TMP_DC_DSC_DIA_SEMANA     := TRIM(TO_CHAR(DATA ,'DAY'));
 	  TMP_DC_DSC_DIA_SEMANA_ABV := TRIM(TO_CHAR(DATA ,'DY'));
	  TMP_DC_DSC_MES 		    := TRIM(TO_CHAR(DATA ,'MONTH'));
	  TMP_DC_DSC_MES_ABREV      := TRIM(TO_CHAR(DATA ,'MON'));
	  TMP_DC_NUM_SEMESTRE       := TO_NUMBER(TO_CHAR(TMP_DC_NUM_ANO) || NUM_SEMESTRE);
	  TMP_DC_NUM_QUADRIMESTRE   := TO_NUMBER(TO_CHAR(TMP_DC_NUM_ANO) || NUM_QUADRIMESTRE);
	  TMP_DC_NUM_TRIMESTRE      := TO_NUMBER(TO_CHAR(TMP_DC_NUM_ANO) || NUM_TRIMESTRE);
	  TMP_DC_NUM_BIMESTRE       := TO_NUMBER(TO_CHAR(TMP_DC_NUM_ANO) || NUM_BIMESTRE);
	  TMP_DC_DSC_SEMESTRE       := TO_NUMBER(NUM_SEMESTRE)     || 'º SEMESTRE DE '     || TO_CHAR(TMP_DC_NUM_ANO);
	  TMP_DC_DSC_QUADRIMESTRE   := TO_NUMBER(NUM_QUADRIMESTRE) || 'º QUADRIMESTRE DE ' || TO_CHAR(TMP_DC_NUM_ANO);
	  TMP_DC_DSC_TRIMESTRE      := TO_NUMBER(NUM_TRIMESTRE)    || 'º TRIMESTRE DE '    || TO_CHAR(TMP_DC_NUM_ANO);
	  TMP_DC_DSC_BIMESTRE       := TO_NUMBER(NUM_BIMESTRE)     || 'º BIMESTRE DE '     || TO_CHAR(TMP_DC_NUM_ANO);
	  TMP_DC_DSC_QUINZENA       := TMP_DC_NUM_QUINZENA || 'º QUINZENA DE '  || TMP_DC_DSC_MES || ' DE ' || TO_CHAR(TMP_DC_NUM_ANO);

	 INSERT INTO HTB_DWCD.DM_DATETIME (
	 	DC_DATETIME_PK, 
	 	DC_DATE, DC_UTIL, 
	 	DC_NUM_DIA, DC_NUM_MES, 
	 	DC_NUM_ANO, 
	 	DC_NUM_ANO_MES, 
	 	DC_NUM_ANO_MES_DIA, 
	 	DC_NUM_DIA_ANO, 
	 	DC_NUM_DIA_SEMANA, 
	 	DC_NUM_SEMANA_MES, 
	 	DC_NUM_SEMANA_ANO, 
	 	DC_NUM_SEMESTRE, 	    
	 	DC_NUM_QUADRIMESTRE, 
	 	DC_NUM_TRIMESTRE, 
	 	DC_NUM_BIMESTRE, 
	 	DC_NUM_QUINZENA, 
		DC_DSC_DIA_SEMANA,    
		DC_DSC_DIA_SEMANA_ABV,
		DC_DSC_MES, 		   
		DC_DSC_MES_ABREV,     
		DC_DSC_SEMESTRE,      
		DC_DSC_QUADRIMESTRE,  
		DC_DSC_TRIMESTRE,     
		DC_DSC_BIMESTRE,      
		DC_DSC_QUINZENA)
      VALUES
      (	TMP_DC_DATETIME_PK,
		TMP_DC_DATE,   
		TMP_DC_UTIL,
		TMP_DC_NUM_DIA,
		TMP_DC_NUM_MES,
		TMP_DC_NUM_ANO,
		TMP_DC_NUM_ANO_MES,
		TMP_DC_NUM_ANO_MES_DIA,
		TMP_DC_NUM_DIA_ANO,
		TMP_DC_NUM_DIA_SEMANA,
		TMP_DC_NUM_SEMANA_MES,
		TMP_DC_NUM_SEMANA_ANO,
		TMP_DC_NUM_SEMESTRE, 
		TMP_DC_NUM_QUADRIMESTRE,
		TMP_DC_NUM_TRIMESTRE,
		TMP_DC_NUM_BIMESTRE,
		TMP_DC_NUM_QUINZENA,
		TMP_DC_DSC_DIA_SEMANA,    
		TMP_DC_DSC_DIA_SEMANA_ABV,
		TMP_DC_DSC_MES, 		   
		TMP_DC_DSC_MES_ABREV,     
		TMP_DC_DSC_SEMESTRE,      
		TMP_DC_DSC_QUADRIMESTRE,  
		TMP_DC_DSC_TRIMESTRE,     
		TMP_DC_DSC_BIMESTRE,      
		TMP_DC_DSC_QUINZENA      
       );
      DATA := DATA + 1;
END LOOP;
COMMIT;
END;