DROP TABLE DM_CO_TEMPO;
ALTER SESSION SET NLS_DATE_LANGUAGE = Portuguese;
CREATE TABLE DM_CO_TEMPO
   (DC_DATA_PK 		  	  NUMBER(10), 
	DC_DATA 			  DATE,    
	DC_UTIL 			  NUMBER(1),
	DC_FERIADO 			  NUMBER(1),
	DC_NUM_DIA 			  NUMBER(2), 
	DC_NUM_MES 			  NUMBER(2),
	DC_NUM_ANO 			  NUMBER(4),
    DC_NUM_ANO_MES        NUMBER(6),
    DC_NUM_ANO_MES_DIA    NUMBER(8),
	DC_NUM_DIA_ANO 		  NUMBER(3),
	DC_NUM_DIA_SEMANA 	  NUMBER(1),
	DC_NUM_SEMANA_MES 	  NUMBER(1),
	DC_NUM_SEMANA_ANO 	  NUMBER(2),
	DC_NUM_SEMESTRE 	  NUMBER(8),
	DC_NUM_QUADRIMESTRE   NUMBER(8),
	DC_NUM_TRIMESTRE 	  NUMBER(8),
	DC_NUM_BIMESTRE 	  NUMBER(8),
	DC_NUM_QUINZENA 	  NUMBER(2),
	DC_DSC_FERIADO 		  VARCHAR2(60),
	DC_DSC_DIA_SEMANA     VARCHAR2(25),
	DC_DSC_DIA_SEMANA_ABV VARCHAR2(10),
	DC_DSC_MES 		      VARCHAR2(20),
	DC_DSC_MES_ABREV      VARCHAR2(10),
	DC_DSC_SEMESTRE       VARCHAR2(120),
	DC_DSC_QUADRIMESTRE   VARCHAR2(120),
	DC_DSC_TRIMESTRE      VARCHAR2(120),
	DC_DSC_BIMESTRE       VARCHAR2(120),
	DC_DSC_QUINZENA       VARCHAR2(120),
	CONSTRAINT   PK_DC_DATA_PK PRIMARY KEY (DC_DATA_PK)
   );

CREATE INDEX IDX_DC_DATA ON HTB_DWCD.DM_CO_TEMPO (DC_DATA);   

DECLARE
	DATA 		DATE;
	DATAINI 	DATE;
	DATAFIM 	DATE;
    TMP_DC_DATA_PK 		  	  NUMBER(10); 
	TMP_DC_DATA 			  DATE     ;
	TMP_DC_UTIL 			  NUMBER(1);
	TMP_DC_FERIADO 			  NUMBER(1);
	TMP_DC_NUM_DIA 			  NUMBER(2);
	TMP_DC_NUM_MES 			  NUMBER(2);
	TMP_DC_NUM_ANO 			  NUMBER(4);
    TMP_DC_NUM_ANO_MES        NUMBER(6);
    TMP_DC_NUM_ANO_MES_DIA    NUMBER(8);
	TMP_DC_NUM_DIA_ANO 		  NUMBER(3);
	TMP_DC_NUM_DIA_SEMANA 	  NUMBER(1);
	TMP_DC_NUM_SEMANA_MES 	  NUMBER(1);
	TMP_DC_NUM_SEMANA_ANO 	  NUMBER(2);
	TMP_DC_NUM_SEMESTRE 	  NUMBER(6);
	TMP_DC_NUM_QUADRIMESTRE   NUMBER(6);
	TMP_DC_NUM_TRIMESTRE 	  NUMBER(6);
	TMP_DC_NUM_BIMESTRE 	  NUMBER(6);
	TMP_DC_NUM_QUINZENA 	  NUMBER(2); 
    TMP_DC_DSC_FERIADO 		  VARCHAR2(60);
	TMP_DC_DSC_DIA_SEMANA     VARCHAR2(25);
	TMP_DC_DSC_DIA_SEMANA_ABV VARCHAR2(10);
	TMP_DC_DSC_MES 		      VARCHAR2(20);
	TMP_DC_DSC_MES_ABREV      VARCHAR2(10);
	TMP_DC_DSC_SEMESTRE       VARCHAR2(120);
	TMP_DC_DSC_QUADRIMESTRE   VARCHAR2(120);
	TMP_DC_DSC_TRIMESTRE      VARCHAR2(120);
	TMP_DC_DSC_BIMESTRE       VARCHAR2(120);
	TMP_DC_DSC_QUINZENA       VARCHAR2(120);
	NUM_SEMESTRE 	  		  VARCHAR2(2);
	NUM_QUADRIMESTRE   		  VARCHAR2(2);
	NUM_TRIMESTRE 	  	  	  VARCHAR2(2);
	NUM_BIMESTRE 	  		  VARCHAR2(2);

BEGIN
  DATAINI := TO_DATE('2000/01/01','YYYY/MM/DD');
  DATAFIM := TO_DATE('2030/12/31','YYYY/MM/DD');
  DATA := DATAINI;
 
WHILE DATA <= DATAFIM LOOP 
      TMP_DC_DATA_PK := TO_NUMBER(TO_CHAR(DATA ,'YYYYMMDD'));
	  TMP_DC_DATA := DATA;     
	  SELECT TO_NUMBER(DECODE(TO_NUMBER(TO_CHAR(DATA ,'D')), 1, '1', 7, '1', '0')) INTO TMP_DC_UTIL FROM DUAL;
	  TMP_DC_NUM_DIA := TO_NUMBER(TO_CHAR(DATA ,'DD'));
	  TMP_DC_NUM_MES := TO_NUMBER(TO_CHAR(DATA ,'MM'));
	  TMP_DC_NUM_ANO := TO_NUMBER(TO_CHAR(DATA ,'YYYY'));
	  TMP_DC_NUM_ANO_MES_DIA := TO_NUMBER(TO_CHAR(DATA ,'YYYYMMDD'));
	  TMP_DC_NUM_ANO_MES 	 := TO_NUMBER(TO_CHAR(DATA ,'YYYYMM')); 
	  TMP_DC_NUM_DIA_ANO 	 := TO_NUMBER(TO_CHAR(DATA ,'DDD'));
	  TMP_DC_NUM_DIA_SEMANA  := TO_NUMBER(TO_CHAR(DATA ,'D'));
	  TMP_DC_NUM_SEMANA_MES  := TO_NUMBER(TO_CHAR(DATA ,'W'));
	  TMP_DC_NUM_SEMANA_ANO  := TO_NUMBER(TO_CHAR(DATA ,'WW')); 
	  SELECT LPAD(TRUNC((TMP_DC_NUM_MES - 1)/6, 0) + 1, 2, '0') INTO NUM_SEMESTRE FROM DUAL;
	  SELECT LPAD(TRUNC((TMP_DC_NUM_MES - 1)/4, 0) + 1, 2, '0') INTO NUM_QUADRIMESTRE FROM DUAL;
	  SELECT LPAD(TRUNC((TMP_DC_NUM_MES - 1)/3, 0) + 1, 2, '0') INTO NUM_TRIMESTRE FROM DUAL;
	  SELECT LPAD(TRUNC((TMP_DC_NUM_MES - 1)/2, 0) + 1, 2, '0') INTO NUM_BIMESTRE FROM DUAL;
	  TMP_DC_NUM_QUINZENA       := TRUNC((TMP_DC_NUM_DIA-1)/15, 0) + 1;
	  TMP_DC_DSC_DIA_SEMANA     := TRIM(TO_CHAR(DATA ,'DAY'));
 	  TMP_DC_DSC_DIA_SEMANA_ABV := TRIM(TO_CHAR(DATA ,'DY'));
	  TMP_DC_DSC_MES 		    := TRIM(TO_CHAR(DATA ,'MONTH'));
	  TMP_DC_DSC_MES_ABREV      := TRIM(TO_CHAR(DATA ,'MON'));
	  TMP_DC_NUM_SEMESTRE       := TO_NUMBER(TO_CHAR(TMP_DC_NUM_ANO) || NUM_SEMESTRE);
	  TMP_DC_NUM_QUADRIMESTRE   := TO_NUMBER(TO_CHAR(TMP_DC_NUM_ANO) || NUM_QUADRIMESTRE);
	  TMP_DC_NUM_TRIMESTRE      := TO_NUMBER(TO_CHAR(TMP_DC_NUM_ANO) || NUM_TRIMESTRE);
	  TMP_DC_NUM_BIMESTRE       := TO_NUMBER(TO_CHAR(TMP_DC_NUM_ANO) || NUM_BIMESTRE);
	  TMP_DC_DSC_SEMESTRE       := TO_NUMBER(NUM_SEMESTRE)     || 'º SEMESTRE DE '     || TO_CHAR(TMP_DC_NUM_ANO);
	  TMP_DC_DSC_QUADRIMESTRE   := TO_NUMBER(NUM_QUADRIMESTRE) || 'º QUADRIMESTRE DE ' || TO_CHAR(TMP_DC_NUM_ANO);
	  TMP_DC_DSC_TRIMESTRE      := TO_NUMBER(NUM_TRIMESTRE)    || 'º TRIMESTRE DE '    || TO_CHAR(TMP_DC_NUM_ANO);
	  TMP_DC_DSC_BIMESTRE       := TO_NUMBER(NUM_BIMESTRE)     || 'º BIMESTRE DE '     || TO_CHAR(TMP_DC_NUM_ANO);
	  TMP_DC_DSC_QUINZENA       := TMP_DC_NUM_QUINZENA || 'º QUINZENA DE '  || TMP_DC_DSC_MES || ' DE ' || TO_CHAR(TMP_DC_NUM_ANO);

	 INSERT INTO HTB_DWCD.DM_CO_TEMPO (
	 	DC_DATA_PK, 
	 	DC_DATA, 
	 	DC_UTIL, 
	 	DC_FERIADO,
	 	DC_NUM_DIA, 
	 	DC_NUM_MES, 
	 	DC_NUM_ANO, 
	 	DC_NUM_ANO_MES, 
	 	DC_NUM_ANO_MES_DIA, 
	 	DC_NUM_DIA_ANO, 
	 	DC_NUM_DIA_SEMANA, 
	 	DC_NUM_SEMANA_MES, 
	 	DC_NUM_SEMANA_ANO, 
	 	DC_NUM_SEMESTRE, 	    
	 	DC_NUM_QUADRIMESTRE, 
	 	DC_NUM_TRIMESTRE, 
	 	DC_NUM_BIMESTRE, 
	 	DC_NUM_QUINZENA, 
	 	DC_DSC_FERIADO,
		DC_DSC_DIA_SEMANA,    
		DC_DSC_DIA_SEMANA_ABV,
		DC_DSC_MES, 		   
		DC_DSC_MES_ABREV,     
		DC_DSC_SEMESTRE,      
		DC_DSC_QUADRIMESTRE,  
		DC_DSC_TRIMESTRE,     
		DC_DSC_BIMESTRE,      
		DC_DSC_QUINZENA)
      VALUES
      (	TMP_DC_DATA_PK,
		TMP_DC_DATA,   
		TMP_DC_UTIL,
		TMP_DC_FERIADO,
		TMP_DC_NUM_DIA,
		TMP_DC_NUM_MES,
		TMP_DC_NUM_ANO,
		TMP_DC_NUM_ANO_MES,
		TMP_DC_NUM_ANO_MES_DIA,
		TMP_DC_NUM_DIA_ANO,
		TMP_DC_NUM_DIA_SEMANA,
		TMP_DC_NUM_SEMANA_MES,
		TMP_DC_NUM_SEMANA_ANO,
		TMP_DC_NUM_SEMESTRE, 
		TMP_DC_NUM_QUADRIMESTRE,
		TMP_DC_NUM_TRIMESTRE,
		TMP_DC_NUM_BIMESTRE,
		TMP_DC_NUM_QUINZENA,
		TMP_DC_DSC_FERIADO,
		TMP_DC_DSC_DIA_SEMANA,    
		TMP_DC_DSC_DIA_SEMANA_ABV,
		TMP_DC_DSC_MES, 		   
		TMP_DC_DSC_MES_ABREV,     
		TMP_DC_DSC_SEMESTRE,      
		TMP_DC_DSC_QUADRIMESTRE,  
		TMP_DC_DSC_TRIMESTRE,     
		TMP_DC_DSC_BIMESTRE,      
		TMP_DC_DSC_QUINZENA      
       );
      DATA := DATA + 1;
END LOOP;
COMMIT;
END;

--SETA FERIADOS (PASCOA, CARNAVAL E CORPUS_CRRIST)
DECLARE
   X           NUMBER;
   Y           NUMBER;
   A           NUMBER;
   B           NUMBER;
   C           NUMBER;
   D           NUMBER;
   E           NUMBER;
   DIA         NUMBER;
   MES         NUMBER;

   ANO_INI 	     				 NUMBER;
   ANO_FIM 	   	 				 NUMBER;
  
   DATA_PASCOA   				 DATE;
   DATA_CARNAVAL 				 DATE;
   DATA_SEXTA_FEIRA_SANTA 		 DATE;
   DATA_CORPUS_CHRISTI    		 DATE;
  
   DATA_PASCOA_LOOKUP 			 NUMBER;
   DATA_SEXTA_FEIRA_SANTA_LOOKUP NUMBER;
   DATA_CARNAVAL_LOOKUP  		 NUMBER;
   DATA_CORPUS_CHRISTI_LOOKUP 	 NUMBER;

BEGIN   
    ANO_INI := 2000;
    ANO_FIM := 2030;
   
    FOR ANO IN ANO_INI..ANO_FIM
  	LOOP
    	    X := 24;
			Y := 5;
		    
			IF ANO > 2099 AND ANO < 2200 THEN 
		      Y := 6;
		    END IF;
		
		   A := ANO MOD 19;
		   B := ANO MOD 4;
		   C := ANO MOD 7;
		   D := (19 * A + X) MOD 30;
		   E := (2 * B + 4 * C + 6 * D + Y) MOD 7;
		
		   IF (D + E) > 9 THEN
		      DIA := D + E - 9;
		      MES := 4;
		   ELSE
		      DIA := D + E + 22;
		      MES := 3;
		   END IF;
		
		   DATA_PASCOA := TO_DATE (DIA || '-' || MES || '-' || ANO, 'DD-MM-YYYY');
		
		   IF MES = 4 AND DIA = 26 THEN
		      DATA_PASCOA := DATA_PASCOA - 7;
		   END IF;
		
		   IF MES = 4 AND DIA = 25 AND D = 28 AND A > 10 THEN
		      DIA := 18;
		      DATA_PASCOA := TO_DATE (DIA || '-' || MES || '-' || ANO, 'DD-MM-YYYY');
		   END IF;
		   
		   DATA_CARNAVAL		  := DATA_PASCOA - 47;
		   DATA_SEXTA_FEIRA_SANTA := DATA_PASCOA - 2;
		   DATA_CORPUS_CHRISTI    := DATA_PASCOA + 60;
		   
		   DATA_PASCOA_LOOKUP     		 := TO_NUMBER(TO_CHAR(DATA_PASCOA, 'YYYYMMDD'));
		   DATA_SEXTA_FEIRA_SANTA_LOOKUP := TO_NUMBER(TO_CHAR(DATA_SEXTA_FEIRA_SANTA, 'YYYYMMDD'));
		   DATA_CARNAVAL_LOOKUP  		 := TO_NUMBER(TO_CHAR(DATA_CARNAVAL, 'YYYYMMDD'));
		   DATA_CORPUS_CHRISTI_LOOKUP 	 := TO_NUMBER(TO_CHAR(DATA_CORPUS_CHRISTI, 'YYYYMMDD'));
		   
		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'PASCOA' WHERE DC_DATA_PK = DATA_PASCOA_LOOKUP;
 		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'PAIXÃO DE CRISTO' WHERE DC_DATA_PK = DATA_SEXTA_FEIRA_SANTA_LOOKUP;
 		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'CARNAVAL' WHERE DC_DATA_PK = DATA_CARNAVAL_LOOKUP;
  		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'CORPUS CHRISTI' WHERE DC_DATA_PK = DATA_CORPUS_CHRISTI_LOOKUP; 		   

   		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'ANO NOVO'  WHERE DC_DATA_PK = TO_NUMBER (ANO || '0101');
   		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'TIRADENTES' WHERE DC_DATA_PK = TO_NUMBER (ANO || '0421');
   		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'DIA DO TRABALHO' WHERE DC_DATA_PK = TO_NUMBER (ANO || '0501');
   		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'INDEPENDÊNCIA DO BRASIL'  WHERE DC_DATA_PK = TO_NUMBER (ANO || '0907');
   		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'NOSSA SR.A APARECIDA'  WHERE DC_DATA_PK = TO_NUMBER (ANO || '1012');
   		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'FINADOS'  WHERE DC_DATA_PK = TO_NUMBER (ANO || '1102');
   		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'PROCLAMAÇÃO DA REPÚBLICA'  WHERE DC_DATA_PK = TO_NUMBER (ANO || '1115');
   		   UPDATE HTB_DWCD.DM_CO_TEMPO SET DC_FERIADO = 1, DC_DSC_FERIADO = 'NATAL'  WHERE DC_DATA_PK = TO_NUMBER (ANO || '1225');
  	END LOOP;
END;